Seperate compilation
UWB-Biocomputing/Graphitti pull request #359
Opened 2022-07-11 18:03 UTC by rashwini21

Professor @stiber , creating this pull request for review. The performance for GPU and CPU input config files(tiny to large) deviate not more than 2 sec. Here is the google spreadsheet for the performance. 

" https://docs.google.com/spreadsheets/d/1WW1iFUQ-m6wms38ipnbmw4X_CgMmMdAKxw0CbkBFYcs/edit?usp=sharing "

2022-07-12 16:02 UTC, stiber requested changes
Mostly minor things. See individual comments.

2022-07-13 02:04 UTC, rashwini21 commented on CMakeLists.txt
> +        set(cuda_sources Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp Simulator/Vertices/Neuro/AllVerticesDeviceFuncs_d.cpp Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp Simulator/Edges/Neuro/
Tried 2 approaches 
1. Use Set() three times to break this long line, but cuda_sources get rewrite everytime we use set. (Not worked)
2. Break cuda_sources to cudaEdges_Source , cudaVertices_Source and cudaConnections_Source and respectively add to Vertices_Source , Edges_Source and Connections_Source but need to add all three variables together when using. (Worked but increases line of code)


Used approach 
Enter each value for cuda_Sources on different line.

2022-07-13 02:04 UTC, rashwini21 commented on CMakeLists.txt
> +        #set(cuda_sources Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp Simulator/Vertices/Neuro/AllVerticesDeviceFuncs_d.cpp)
Removed previous comments now

2022-07-13 20:34 UTC, rashwini21 commented on CMakeLists.txt
>  file(GLOB_RECURSE Edges_Source Simulator/Edges/*.cpp Simulator/Edges/*.h Simulator/Edges/*.cu)
Removed .cu from the Edges_Source ,No .cu files left in Edges_Source. .cu files 2 files left in Simulator/Utils and .cu files in mersenne twister.

2022-07-13 20:35 UTC, rashwini21 commented on CMakeLists.txt
>  file(GLOB Core_Source Simulator/Core/*.cpp Simulator/Core/*.h Simulator/Core/*.cu)
Removed .cu from the Core_Source ,No .cu files left in Core_Source. .cu files 2 files left in Simulator/Utils and .cu files in mersenne twister.

2022-07-13 20:35 UTC, rashwini21 commented on CMakeLists.txt
>  # Set CUDA_SEPERABLE_COMPILATION to ON for all libraries that contain .cu CUDA files
Changed Reference here

2022-07-13 20:36 UTC, rashwini21 commented on Simulator/Edges/Neuro/AllSynapsesDeviceFuncs.h
> +// extern CUDA_CALLABLE void changeSpikingSynapsesPSRDevice(AllSpikingSynapsesDeviceProperties* allEdgesDevice, const BGSIZE iEdg, const uint64_t simulationStep, const BGFLOAT deltaT);
Removed the commented out code.

2022-07-13 20:36 UTC, rashwini21 commented on Simulator/Vertices/Neuro/AllVerticesDeviceFuncs.h
> +// extern __global__ void advanceLIFNeuronsDevice( int totalVertices, int maxEdges, int maxSpikes, const BGFLOAT deltaT, uint64_t simulationStep, float* randNoise, AllIFNeuronsDeviceProperties* allVe
Removed here

2022-07-13 20:36 UTC, rashwini21 commented on Simulator/Vertices/Neuro/AllVerticesDeviceFuncs.h
> +/// extern __global__ void advanceIZHNeuronsDevice( int totalVertices, int maxEdges, int maxSpikes, const BGFLOAT deltaT, uint64_t simulationStep, float* randNoise, AllIZHNeuronsDeviceProperties* all
Removed here

2022-07-13 22:21 UTC, stiber commented on CMakeLists.txt
> +        set(cuda_sources Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp Simulator/Vertices/Neuro/AllVerticesDeviceFuncs_d.cpp Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp Simulator/Edges/Neuro/
So, you can’t just split it over multiple lines or use a “\”? Just curious.

2022-07-13 22:24 UTC, stiber commented on CMakeLists.txt
> +        set(cuda_sources Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp Simulator/Vertices/Neuro/AllVerticesDeviceFuncs_d.cpp Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp Simulator/Edges/Neuro/
Never mind; that’s what you did!

2022-07-15 19:38 UTC, rashwini21 commented
Hi Professor @stiber , we can merge this branch now. Tested all clang-format changes on CPU and GPU Outputs ,no change in any output or time of running input config files. I  will now check the time change during compilation.

2022-07-15 21:52 UTC, stiber approved these changes

2022-07-15 22:13 UTC, merged