Basic CircularBuffer class
UWB-Biocomputing/Graphitti pull request #398
Opened 2023-01-31 05:22 UTC by jardiamj

This is a basic CircularBuffer class intended to be used in the implementation of the NG-911 Discrete Event Queueing model.

In the current implementation, the `get()` method returns a default constructed object when called on an empty buffer. If we decide that it's worth it, we could move our target standard to C++17 and take advantage of the `std::optional` data type. The main advantage is that we will get an obviously invalid value in such a case.

2023-01-31 17:28 UTC, stiber requested changes
Since you raise the issue of C++17, consult with @KamathScience on her future plans for presenting language features and when the feels that she would be ready to facilitate a discussion of which C++ version we should target. My guess is that it will be C++17, but let's make sure we have heard about the key features at each step and any gotcha's.

2023-01-31 17:28 UTC, stiber commented on Simulator/Utils/CircularBuffer.h
> +
`#pragma once`?

2023-02-01 01:22 UTC, KamathScience commented
> Since you raise the issue of C++17, consult with @KamathScience on her future plans for presenting language features and when the feels that she would be ready to facilitate a discussion of which C++ version we should target. My guess is that it will be C++17, but let's make sure we have heard about the key features at each step and any gotcha's.

I support upgrading the codebase to C++17 (many C++11 features are refined and polished in C++14 and C++17). The only reservation I have is with GPU - I am not sure if upgrading to C++17 would affect the GPU code/working.

2023-02-17 18:40 UTC, stiber approved these changes

2023-02-19 08:00 UTC, merged