issue-427: Removed #ifndef against #pragma once in all .h files in Simulator
UWB-Biocomputing/Graphitti pull request #433
Opened 2023-04-12 00:46 UTC by Sanchit-kumar

Closes #427 
Following changes made in .h files present in Simulator:
1. Added #pragma once if missing
2. Removed #ifndef if required
3. Removed extra tab for the indentation if required

2023-04-12 18:27 UTC, stiber requested changes
Some "orphan" `#define`s left over that are no longer needed.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Book.h
>  #define __BOOK_H__
Should be deleted.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Coordinate.h
>  #define _COORDINATE_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Global.h
> +#define _GLOBAL_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/FSInput.h
> +#define _FSINPUT_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/GpuSInputPoisson.h
> +#define _GPUSINPUTPOISSON_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/GpuSInputRegular.h
> +#define _GPUSINPUTREGULAR_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/HostSInputPoisson.h
> +#define _HOSTSINPUTPOISSON_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/HostSInputRegular.h
> +#define _HOSTSINPUTREGULAR_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/ISInput.h
> +#define _ISINPUT_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/SInputPoisson.h
> +#define _SINPUTPOISSON_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Inputs/SInputRegular.h
> +#define _SINPUTREGULAR_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Matrix/Matrix.h
>  #define _MATRIX_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Matrix/MatrixFactory.h
>  #define _MATRIXFACTORY_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Matrix/SparseMatrix.h
>  #define _SPARSEMATRIX_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Matrix/VectorMatrix.h
>  #define _VECTORMATRIX_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/ParseParamError.h
>  #define _PARSEPARAMERROR_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/RNG/MersenneTwister_d.h
> +#define mersennetwister_h
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/RNG/Norm.h
>  #define _NORM_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Timer.h
>  #define _TIMER_H_
Delete.

2023-04-12 18:27 UTC, stiber commented on Simulator/Utils/Util.h
> +#define _UTIL_H_
Delete.

2023-04-14 18:25 UTC, stiber commented
I think one more file waiting (see unresolved conversation).

2023-04-17 20:09 UTC, stiber commented
It seems that this PR is failing our style check. If it isn't obvious what the issues are, you might try running a recent version of `clang-format` to generate a reformatted version of the file(s) in question, and then do a `diff` to see what it's unhappy about. Sometimes, this is extra spaces or tabs instead of spaces or the like. Our GitHub Pages has some more documentation about this.

2023-04-19 08:01 UTC, Sanchit-kumar commented
I missed a few files for code style check. Updated the code style with respect to .clang-format file.

2023-04-24 17:42 UTC, stiber approved these changes

2023-05-11 21:27 UTC, merged