[ISSUE 376] Rename command line options for stimulusfile (-s), deserializefile(-r) and serializefile(-w)
UWB-Biocomputing/Graphitti pull request #494
Opened 2023-08-02 00:50 UTC by Andrzej-Dawiec

- Renames command line options for stimulusfile (-s), deserializefile(-r) and serializefile(-w)
- Updates the command line option in the documentation under Student Quickstart
- Adds command line option in the documentation under Quickstart

2023-08-10 17:49 UTC, stiber requested changes

2023-08-10 17:49 UTC, stiber commented on Simulator/Core/Core.cpp
> +       || (cl.addParam("device", 'g', ParamContainer::regular, "CUDA device id")
To make the hint explain more clearly why it's `-g`, let's make it `"CUDA GPU device ID"`

2023-08-10 17:49 UTC, stiber commented on Simulator/Core/Core.cpp
> +#endif   // USE_GPU changed 'd' to 'g' option
I don't think it's necessary to have a note about the change in the comment here.

2023-08-10 17:49 UTC, stiber commented on docs/Developer/StudentSetup.md
> +- `-s, --serializefile=<serializefile>`: Specifies the filepath for simulation serialization. Enabling this option allows you to serialize the simulation.
Is there a note about the `-g` option in this file?

2023-08-10 17:49 UTC, stiber commented on docs/User/quickstart.md
> +- `-v, --version`: Outputs the current git commit ID and exits.
Is there a note about the `-g` option in this file?

2024-05-28 22:27 UTC, jardiamj commented
I took care of the requested changes to attempt merging this PR.

2024-06-02 18:14 UTC, stiber approved these changes

2024-06-03 06:42 UTC, merged