Issue 495 visualization from graph ml
UWB-Biocomputing/Graphitti pull request #544
Opened 2023-10-11 01:08 UTC by silvercube227

resolves #495 

Created a visualization of King County 911 system from GraphML data. Color coded nodes for ease of use.

2023-10-12 21:11 UTC, stiber requested changes
This branch is off of `master`, but should be off of `development`. Figure some good way to get this to merge into `development`.

2023-10-12 21:11 UTC, stiber commented on Tools/gis2graph/__pycache__/random.cpython-310.pyc
Delete this from the repo, add `__pycache__` to the `.gitignore`, and tell git to untrack this stuff.

2023-10-12 21:11 UTC, stiber commented on Tools/gis2graph/visualize_graphML.py
Move to `Tools/graphMLVis`

2023-10-18 21:52 UTC, whiteja2 commented on Tools/gis2graph/__pycache__/random.cpython-310.pyc
__pycache__ has been removed, added to the .gitignore, and untracked.

2023-10-18 21:52 UTC, whiteja2 commented on Tools/gis2graph/visualize_graphML.py
visualize_graphML.py has been moved to the graphMLVis directory.

2023-10-19 21:10 UTC, stiber approved these changes

2023-10-19 21:13 UTC, merged