[ISSUE-616] Update Recorder diagrams and documentation/Notes
UWB-Biocomputing/Graphitti pull request #631
Opened 2024-04-22 21:35 UTC by xiangli6

closes #616 

After completing the redesigned XmlRecorder implementation, three files need to be updated for documentation:

1. Add a sequential diagram for the Recorder workflow (including the XmlRecorder and HDF5Recorder.
2. Include a Recorder Class Diagram.
3. Update the GitHub Page with Recorder Notes (Section 4.6). I formatted the previous Recorder notes and added the redesigned XmlRecorder notes.

2024-04-23 16:47 UTC, stiber approved these changes

2024-04-23 16:56 UTC, stiber requested changes
Could you move the "How the Redesigned Recorder Works (Q1 2024)" section of `RecorderNotes.md` near the top of the file, with the legacy documentation below it?

2024-04-24 04:31 UTC, xiangli6 commented
> Could you move the "How the Redesigned Recorder Works (Q1 2024)" section of `RecorderNotes.md` near the top of the file, with the legacy documentation below it?

Sure, I have updated the page

2024-04-25 21:19 UTC, stiber approved these changes

2024-04-26 14:41 UTC, merged