[ISSUE 371] Refactor Neural X Y Init
UWB-Biocomputing/Graphitti pull request #646
Opened 2024-05-11 16:58 UTC by Oelgazz

closes #371

2024-05-19 07:43 UTC, jardiamj commented
This looks good. There are just some empty lines and 4-space indentations that clang-format complains about in the C++ code and one small suggestion for the Python script.

2024-05-19 07:51 UTC, jardiamj commented
I have one question about the purpose of the Python script. Is it meant to be a tool for generating the neural network graph,  with x and y locations, for a given grid size (e.g. 10x10, 100x100)? if so, it might be more useful for the script to accept the grid size,  through the command line for example.

2024-05-19 17:02 UTC, Oelgazz commented
The purpose of the python script is to be a tool for users to generate GraphML files for the neural simulator. This script is the initial version and is updated in other branches to include parameters such as inhibitory and endogenously active neuron lists (see issues #641  and #642 ).

Because of this, it will be difficult for a user to input these details through the command line, as they will need to at least include the grid size, the inhibitory neuron list, the endogenously active neuron list, and the graph name.  Also, since using GraphML will allow the possibility of having non-grid layouts, the grid size may become a (x,y) tuple list.

2024-05-20 05:18 UTC, jardiamj commented
> The purpose of the python script is to be a tool for users to generate GraphML files for the neural simulator. This script is the initial version and is updated in other branches to include parameters such as inhibitory and endogenously active neuron lists (see issues #641 and #642 ).
> 
> Because of this, it will be difficult for a user to input these details through the command line, as they will need to at least include the grid size, the inhibitory neuron list, the endogenously active neuron list, and the graph name. Also, since using GraphML will allow the possibility of having non-grid layouts, the grid size may become a (x,y) tuple list.

Great! That makes sense.

2024-05-30 05:41 UTC, jardiamj requested changes

2024-05-30 23:05 UTC, Oelgazz commented on Simulator/Layouts/Layout.cpp
>     // initial graph
This TODO is resolved in issue #642

2024-05-30 23:06 UTC, Oelgazz commented on Simulator/Layouts/Neuro/LayoutNeuro.cpp
> +    // TODO: Currently not fully implemented because Neuro model is still integrating graphML
This TODO is resolved in issue #642

2024-05-31 04:18 UTC, jardiamj approved these changes

2024-05-31 19:26 UTC, merged